[MegaLinter] Apply linters automatic fixes

diff --git a/.github/workflows/Deployment.yaml b/.github/workflows/Deployment.yaml
--- a/.github/workflows/Deployment.yaml
+++ b/.github/workflows/Deployment.yaml
@@ -17,7 +17,7 @@ jobs:
       issues: write
       pull-requests: write
       statuses: write
-      
+
   pyinstaller-build:
     runs-on: windows-latest
     steps:
@@ -30,13 +30,13 @@ jobs:
         uses: actions/checkout@v4
       - name: Verify Version
         run: |
-            TAG_VERSION=${GITHUB_REF#refs/tags/v}
-            TOML_VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
-            if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
-              echo "Version mismatch: tag is $TAG_VERSION but pyproject.toml is $TOML_VERSION"
-              exit 1  # Exits with a non-zero status to fail the workflow
-            fi
-        shell: bash 
+          TAG_VERSION=${GITHUB_REF#refs/tags/v}
+          TOML_VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
+          if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
+            echo "Version mismatch: tag is $TAG_VERSION but pyproject.toml is $TOML_VERSION"
+            exit 1  # Exits with a non-zero status to fail the workflow
+          fi
+        shell: bash
       - name: Create GitHub release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
