updated deployment

diff --git a/.github/workflows/Deployment.yaml b/.github/workflows/Deployment.yaml
--- a/.github/workflows/Deployment.yaml
+++ b/.github/workflows/Deployment.yaml
@@ -6,43 +6,42 @@ name: Deployment
 
 on:
   push:
-    branches:
-      - "main"
-  pull_request:
-    branches:
-      - "main"
+    tags:
+      - "v[0-9]+.[0-9]+.[0-9]+"
 
 jobs:
+  linting:
+    uses: ./.github/workflows/mega-linter.yaml
+    permissions:
+      contents: write
+      issues: write
+      pull-requests: write
+      statuses: write
+      
   pyinstaller-build:
     runs-on: windows-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Install Python
-        uses: actions/setup-python@v4
-        # see details (matrix, python-version, python-version-file, etc.)
-        # https://github.com/actions/setup-python
-        with:
-          python-version: '3.12' 
-      - name: Install poetry
-        uses: abatilo/actions-poetry@v4
-      - name: Setup a local virtual environment (if no poetry.toml file)
+      - name: Check if on main branch
+        if: github.ref != 'refs/heads/main'
         run: |
-          poetry config virtualenvs.create true --local
-          poetry config virtualenvs.in-project true --local
-      - uses: actions/cache@v3
-        name: Define a cache for the virtual environment based on the dependencies lock file
-        with:
-          path: ./.venv
-          key: venv-${{ hashFiles('poetry.lock') }}
-      - name: Create requirements.txt
+          echo "This Tag is not on the main branch!"
+          exit 1
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Verify Version
         run: |
-          poetry self add poetry-plugin-export
-          poetry export -f requirements.txt --output requirements.txt
-      - name: Create Executable
-        uses: sayyid5416/pyinstaller@v1
+            TAG_VERSION=${GITHUB_REF#refs/tags/v}
+            TOML_VERSION=$(grep '^version =' pyproject.toml | sed -E 's/version = "([^"]+)"/\1/')
+            if [ "$TAG_VERSION" != "$TOML_VERSION" ]; then
+              echo "Version mismatch: tag is $TAG_VERSION but pyproject.toml is $TOML_VERSION"
+              exit 1  # Exits with a non-zero status to fail the workflow
+            fi
+        shell: bash 
+        # TODO: Make work with pyproject.toml
+      - uses: sayyid5416/pyinstaller@v1
         with:
           python_ver: "3.12"
           spec: "main.py"
-          requirements: "requirements.txt"
-          upload_exe_with_name: "Fly Swapper 3000"
-          options: --onefile, --name "Fly Swapper 3000", --icon ".\docs\\SG Logo.ico", --add-data ".\docs\;docs"
+          requirements: "./requirements.txt"
+          upload_exe_with_name: "Fly Plotter 4000"
+          options: --onefile, --name "Fly Plotter 4000", --icon ".\docs\\SG Logo.ico", --add-data ".\docs\;docs"
